<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Média escolar</title>
</head>
<body>
    <p>
        Crie um programa que deve ser inerido em um vetor as notas bimestrais de um aluno e uma função para realizar este
        cadastro via formulario do php, neste caso necessito do arquivo html e php;
        realize a média e a situação entre aprovado, recuperação e reprovado.
        Valide as entradas das notas via JavaScripit, para o backend receber apenas 
        as notas validas de 0 á 10.
        mesmo assim valide as entradas também em PHP.
    </p>

</body>
</html>

