<?php

$numeroAleatorio = rand(0,10);
    
    
    $numeroEntrada =$_POST['numeroEntrada'];

    switch($numeroAleatorio){
        case 0:
            if($numeroEntrada  == $numeroAleatorio ){
            echo "Parabens";
        }else "tente novamente";
            break;//Sair da lista
        case 1:
            if($numeroEntrada  == $numeroAleatorio ){
                echo "Parabens";
            }else "tente novamente";
            break;
        case 2:
            if($numeroEntrada  == $numeroAleatorio ){
                echo "Parabens";
            }else "tente novamente";
            break;
        case 3:
            if($numeroEntrada  == $numeroAleatorio ){
                echo "Parabens";
            }else "tente novamente";
            break;
        case 4:
            if($numeroEntrada  == $numeroAleatorio ){
                echo "Parabens";
            }else "tente novamente";
        case 5:
            if($numeroEntrada  == $numeroAleatorio ){
                echo "Parabens";
            }else "tente novamente";
            break;
        case 6:
            if($numeroEntrada  == $numeroAleatorio ){
                echo "Parabens";
            }else "tente novamente";
            break;
        case 7:
            if($numeroEntrada  == $numeroAleatorio ){
                echo "Parabens";
            }else "tente novamente";
            break;
        case 8:
            if($numeroEntrada  == $numeroAleatorio ){
                echo "Parabens";
            }else "tente novamente";
            break;
        case 9:
            if($numeroEntrada  == $numeroAleatorio ){
                echo "Parabens";
            }else "tente novamente";
            break;
        case 10:
            if($numeroEntrada  == $numeroAleatorio ){
                echo "Parabens";
            }else "tente novamente";
            break;        
    }



?>